sudo: false
language: generic
matrix:
    include:

        # Linux
        - os: linux
          env: PYTHON_VERSION=3.6

        - os: linux
          env: PYTHON_VERSION=3.7

        # OSX
        - os: osx
          env: PYTHON_VERSION=3.6 MPLBACKEND=Agg

        - os: osx
          env: PYTHON_VERSION=3.7 MPLBACKEND=Agg

install:
    - source .ci/travis.sh

script:
    - nosetests -v isochrones
