sudo: false
language: c
matrix:
    include:

        # Linux
        - os: linux
          env: PYTHON_VERSION=3.6

        # OSX
        - os: osx
          env: PYTHON_VERSION=3.6

install:
    - source .ci/travis.sh

script:
    - nosetests -v isochrones
