sudo: false
language: generic
matrix:
    include:

        # Linux
        - os: linux
          env: PYTHON_VERSION=3.6

        - os: linux
          env: PYTHON_VERSION=3.7

        - os: linux
          env: PYTHON_VERSION=3.8

        # OSX
        - os: osx
          env: PYTHON_VERSION=3.6 MPLBACKEND=Agg

        - os: osx
          env: PYTHON_VERSION=3.7 MPLBACKEND=Agg

        - os: osx
          env: PYTHON_VERSION=3.8 MPLBACKEND=Agg

install:
    - source .ci/travis.sh

script:
    - df -h
    - mist-initialize.py  # sidestep long-running tests by running this first
    - pytest -v
    # - set -e
    # - python3 -m sphinx docs docs/_build
    # - pip install doctr
    # - doctr deploy --built-docs docs/_build/html . --branch-whitelist bolo

# after_success:
#   - codecov # submit coverage
