name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  style:
    name: "Check the Python code style"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Check style
        run: |
          python -m pip install -U pip
          python -m pip install -U flake8
          python -m flake8 isochrones --ignore=E501,W503,E741,E203,E266,E731,E128

  script:
    name: "Test that the init script works w/o cache"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: 3.8
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install -c conda-forge multinest pymultinest "numba<0.53.0" "pandas<1.1" numpy
          python -m pip install -U pip
          python -m pip install -e ".[test]"
      - name: Initialize the MIST grids
        shell: bash -l {0}
        run: |
          mist-initialize.py
      - name: Run tests
        shell: bash -l {0}
        run: python -m pytest -v

  tests:
    name: "${{ matrix.os }} / py${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8"]
        os: [ubuntu-latest, macos-latest]
        exclude:  # Don't duplicate work from above
          - python-version: "3.8"
            os: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download data files
        run: |
          wget -q -O ~/isochrones.zip "https://zenodo.org/record/4056544/files/isochrones.zip?download=1"
          unzip ~/isochrones.zip -d ~
      - name: Set up Python ${{ matrix.python-version }}
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install "numba<0.53.0"
          conda install -c conda-forge multinest pymultinest
          python -m pip install -U pip
          python -m pip install -U -e ".[test]"
      - name: Run tests
        shell: bash -l {0}
        run: python -m pytest -v
